UPDATE "holiday" SET "image" = '/uploads/holidays/new-years.jpg' WHERE "id" = 'evt-001';
UPDATE "kit" SET "images" = ARRAY['/events/ny-starter-2026_angle1.jpg', '/events/ny-starter-2026_angle2.jpg', '/events/ny-starter-2026_angle3.jpg', '/events/ny-starter-2026_angle4.jpg'] WHERE "sku" = 'NY-STARTER-2026';
UPDATE "kit" SET "images" = ARRAY['/events/ny-premium-2026_angle1.jpg', '/events/ny-premium-2026_angle2.jpg', '/events/ny-premium-2026_angle3.jpg', '/events/ny-premium-2026_angle4.jpg'] WHERE "sku" = 'NY-PREMIUM-2026';
UPDATE "holiday" SET "image" = '/uploads/holidays/ramadan.jpg' WHERE "id" = 'evt-002';
UPDATE "kit" SET "images" = ARRAY['/events/ram-starter-2026_angle1.jpg', '/events/ram-starter-2026_angle2.jpg', '/events/ram-starter-2026_angle3.jpg', '/events/ram-starter-2026_angle4.jpg'] WHERE "sku" = 'RAM-STARTER-2026';
UPDATE "kit" SET "images" = ARRAY['/events/ram-premium-2026_angle1.jpg', '/events/ram-premium-2026_angle2.jpg', '/events/ram-premium-2026_angle3.jpg', '/events/ram-premium-2026_angle4.jpg'] WHERE "sku" = 'RAM-PREMIUM-2026';
UPDATE "holiday" SET "image" = '/uploads/holidays/diwali.jpg' WHERE "id" = 'evt-003';
UPDATE "kit" SET "images" = ARRAY['/events/diw-starter-2026_angle1.jpg', '/events/diw-starter-2026_angle2.jpg', '/events/diw-starter-2026_angle3.jpg', '/events/diw-starter-2026_angle4.jpg'] WHERE "sku" = 'DIW-STARTER-2026';
UPDATE "kit" SET "images" = ARRAY['/events/diw-premium-2026_angle1.jpg', '/events/diw-premium-2026_angle2.jpg', '/events/diw-premium-2026_angle3.jpg', '/events/diw-premium-2026_angle4.jpg'] WHERE "sku" = 'DIW-PREMIUM-2026';
UPDATE "holiday" SET "image" = '/uploads/holidays/valentines-day.jpg' WHERE "id" = 'evt-005';
UPDATE "kit" SET "images" = ARRAY['/events/val-starter-2026_angle1.jpg', '/events/val-starter-2026_angle2.jpg', '/events/val-starter-2026_angle3.jpg', '/events/val-starter-2026_angle4.jpg'] WHERE "sku" = 'VAL-STARTER-2026';
UPDATE "kit" SET "images" = ARRAY['/events/val-premium-2026_angle1.jpg', '/events/val-premium-2026_angle2.jpg', '/events/val-premium-2026_angle3.jpg', '/events/val-premium-2026_angle4.jpg'] WHERE "sku" = 'VAL-PREMIUM-2026';
UPDATE "holiday" SET "image" = '/uploads/holidays/nowruz.jpg' WHERE "id" = 'evt-006';
UPDATE "kit" SET "images" = ARRAY['/events/now-starter-2026_angle1.jpg', '/events/now-starter-2026_angle2.jpg', '/events/now-starter-2026_angle3.jpg', '/events/now-starter-2026_angle4.jpg'] WHERE "sku" = 'NOW-STARTER-2026';
UPDATE "kit" SET "images" = ARRAY['/events/now-premium-2026_angle1.jpg', '/events/now-premium-2026_angle2.jpg', '/events/now-premium-2026_angle3.jpg', '/events/now-premium-2026_angle4.jpg'] WHERE "sku" = 'NOW-PREMIUM-2026';
UPDATE "holiday" SET "image" = '/uploads/holidays/baby-showers.jpg' WHERE "id" = 'evt-007';
UPDATE "kit" SET "images" = ARRAY['/events/baby-starter-2026_angle1.jpg', '/events/baby-starter-2026_angle2.jpg', '/events/baby-starter-2026_angle3.jpg', '/events/baby-starter-2026_angle4.jpg'] WHERE "sku" = 'BABY-STARTER-2026';
UPDATE "kit" SET "images" = ARRAY['/events/baby-premium-2026_angle1.jpg', '/events/baby-premium-2026_angle2.jpg', '/events/baby-premium-2026_angle3.jpg', '/events/baby-premium-2026_angle4.jpg'] WHERE "sku" = 'BABY-PREMIUM-2026';
UPDATE "holiday" SET "image" = '/uploads/holidays/eid.jpg' WHERE "id" = 'evt-009';
UPDATE "kit" SET "images" = ARRAY['/events/eid-starter-2026_angle1.jpg', '/events/eid-starter-2026_angle2.jpg', '/events/eid-starter-2026_angle3.jpg', '/events/eid-starter-2026_angle4.jpg'] WHERE "sku" = 'EID-STARTER-2026';
UPDATE "kit" SET "images" = ARRAY['/events/eid-premium-2026_angle1.jpg', '/events/eid-premium-2026_angle2.jpg', '/events/eid-premium-2026_angle3.jpg', '/events/eid-premium-2026_angle4.jpg'] WHERE "sku" = 'EID-PREMIUM-2026';
UPDATE "holiday" SET "image" = '/uploads/holidays/engagement-parties.jpg' WHERE "id" = 'evt-010';
UPDATE "kit" SET "images" = ARRAY['/events/eng-starter-2026_angle1.jpg', '/events/eng-starter-2026_angle2.jpg', '/events/eng-starter-2026_angle3.jpg', '/events/eng-starter-2026_angle4.jpg'] WHERE "sku" = 'ENG-STARTER-2026';
UPDATE "kit" SET "images" = ARRAY['/events/eng-premium-2026_angle1.jpg', '/events/eng-premium-2026_angle2.jpg', '/events/eng-premium-2026_angle3.jpg', '/events/eng-premium-2026_angle4.jpg'] WHERE "sku" = 'ENG-PREMIUM-2026';
UPDATE "holiday" SET "image" = '/uploads/holidays/halloween.jpg' WHERE "id" = 'evt-011';
UPDATE "kit" SET "images" = ARRAY['/events/hal-starter-2026_angle1.jpg', '/events/hal-starter-2026_angle2.jpg', '/events/hal-starter-2026_angle3.jpg', '/events/hal-starter-2026_angle4.jpg'] WHERE "sku" = 'HAL-STARTER-2026';
UPDATE "kit" SET "images" = ARRAY['/events/hal-premium-2026_angle1.jpg', '/events/hal-premium-2026_angle2.jpg', '/events/hal-premium-2026_angle3.jpg', '/events/hal-premium-2026_angle4.jpg'] WHERE "sku" = 'HAL-PREMIUM-2026';
UPDATE "holiday" SET "image" = '/uploads/holidays/hanukkah.jpg' WHERE "id" = 'evt-012';
UPDATE "kit" SET "images" = ARRAY['/events/han-starter-2026_angle1.jpg', '/events/han-starter-2026_angle2.jpg', '/events/han-starter-2026_angle3.jpg', '/events/han-starter-2026_angle4.jpg'] WHERE "sku" = 'HAN-STARTER-2026';
UPDATE "kit" SET "images" = ARRAY['/events/han-premium-2026_angle1.jpg', '/events/han-premium-2026_angle2.jpg', '/events/han-premium-2026_angle3.jpg', '/events/han-premium-2026_angle4.jpg'] WHERE "sku" = 'HAN-PREMIUM-2026';
